# Generated by Django 5.1.5 on 2025-01-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
