# Generated by Django 5.1.5 on 2025-01-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers_userresetpasswordtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='')),
                ('about', models.TextField(blank=True, default='Нет информации.')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='Не указан', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
