# Generated by Django 5.1.5 on 2025-01-25 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
