# Generated by Django 5.1.5 on 2025-01-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
